#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 4
#SBATCH --ntasks-per-node 28
#SBATCH --cpus-per-task=1
#SBATCH --time 00:02:30
#SBATCH --output 1024x1024.out

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`
                                                                 
module load OpenMPI/1.10.2-GCC-4.9.3-2.25      

#! Run the executable
mpirun ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
